CREATE TABLE IF NOT EXISTS public.contracts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type TEXT NOT NULL,
  status TEXT NOT NULL,
  buyer_id UUID NOT NULL,
  seller_id UUID NOT NULL,
  buyer_name TEXT NOT NULL,
  seller_name TEXT NOT NULL,
  product_type TEXT NOT NULL,
  incoterm TEXT NOT NULL,
  quantity TEXT NOT NULL,
  allowed_variance TEXT NOT NULL,
  unit_price TEXT NOT NULL,
  currency TEXT NOT NULL,
  payment_terms TEXT NOT NULL,
  quality_ffa TEXT NOT NULL,
  quality_iv TEXT NOT NULL,
  quality_s TEXT NOT NULL,
  quality_m1 TEXT NOT NULL,
  packing_standard TEXT NOT NULL,
  origin_country TEXT NOT NULL,
  delivery_country TEXT NOT NULL,
  delivery_port TEXT NOT NULL,
  loading_start_date TEXT NOT NULL,
  loading_period TEXT NOT NULL,
  loading_duration TEXT NOT NULL,
  delivery_date TEXT NOT NULL,
  external_reference_id TEXT,
  broker JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_by UUID REFERENCES public.users(id),
  updated_by UUID REFERENCES public.users(id)
);

alter publication supabase_realtime add table contracts;
